import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Components
import Button from "@/components/Button/Button";
import Nav from "@/components/Nav/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        <section className="bg-yellow-500/50 h-10 w-full flex items-center justify-center px-5 shadow-lg gap-5">
          <Button extraclasses="!py-1">Create Pizza</Button>
          <Button extraclasses="!py-1">Manage Orders</Button>
          <Button extraclasses="!py-1">Admin Settings</Button>
        </section>
        {children}
      </body>
    </html>
  );
}
