import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-orange-500 h-16 w-full flex items-center px-5 shadow-lg gap-5">
          <h1 className="text-white text-3xl">Pizzaio | admin</h1>
          <button>Test</button>
        </div>
        {children}
      </body>
    </html>
  );
}
